//
//  UILabel+Night.h
//  UILabel+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UILabel (Night)

@property (nonatomic, copy, setter = setTextColorPicker:) DKColorPicker textColorPicker;
@property (nonatomic, copy, setter = setShadowColorPicker:) DKColorPicker shadowColorPicker;
@property (nonatomic, copy, setter = setHighlightedTextColorPicker:) DKColorPicker highlightedTextColorPicker;

@end
