//
//  UIPageControl+Night.m
//  UIPageControl+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIPageControl+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UIPageControl ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;
@property (nonatomic, strong) NSMutableDictionary<NSString *, id> *imagePickers;

@end

@implementation UIPageControl (Night)

- (DKColorPicker)pageIndicatorTintColorPicker {
   
   return objc_getAssociatedObject(self, @selector(pageIndicatorTintColorPicker));
}

- (void)setPageIndicatorTintColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(pageIndicatorTintColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);

   if (nil != aPicker) {
      
      self.pageIndicatorTintColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setPageIndicatorTintColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setPageIndicatorTintColor:"];
      
   } /* End else */
   
   return;
}

- (DKColorPicker)currentPageIndicatorTintColorPicker {
   
   return objc_getAssociatedObject(self, @selector(currentPageIndicatorTintColorPicker));
}

- (void)setCurrentPageIndicatorTintColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(currentPageIndicatorTintColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);
   
   if (nil != aPicker) {
      
      self.currentPageIndicatorTintColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setCurrentPageIndicatorTintColor:"];

   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setCurrentPageIndicatorTintColor:"];
      
   } /* End else */
      
   return;
}

@end
