//
//  UIProgressView+Night.m
//  UIProgressView+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIProgressView+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UIProgressView ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIProgressView (Night)

- (DKColorPicker)progressTintColorPicker {
   
   return objc_getAssociatedObject(self, @selector(progressTintColorPicker));
}

- (void)setProgressTintColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(progressTintColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);
   
   if (nil != aPicker) {
      
      self.progressTintColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setProgressTintColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setProgressTintColor:"];
      
   } /* End else */
   
   return;
}

- (DKColorPicker)trackTintColorPicker {
   
   return objc_getAssociatedObject(self, @selector(trackTintColorPicker));
}

- (void)setTrackTintColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(trackTintColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);

   if (nil != aPicker) {
      
      self.trackTintColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setTrackTintColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setTrackTintColor:"];
      
   } /* End else */
   
   return;
}

@end
