//
//  UISlider+Night.h
//  UISlider+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UISlider (Night)

@property (nonatomic, copy, setter = setMinimumTrackTintColorPicker:) DKColorPicker minimumTrackTintColorPicker;
@property (nonatomic, copy, setter = setMaximumTrackTintColorPicker:) DKColorPicker maximumTrackTintColorPicker;
@property (nonatomic, copy, setter = setThumbTintColorPicker:) DKColorPicker thumbTintColorPicker;

@end
