//
//  UISwitch+Night.h
//  UISwitch+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UISwitch (Night)

@property (nonatomic, copy, setter = setOnTintColorPicker:) DKColorPicker onTintColorPicker;
@property (nonatomic, copy, setter = setThumbTintColorPicker:) DKColorPicker thumbTintColorPicker;

@property (nonatomic, copy, setter = setOnImagePicker:) DKImagePicker onImagePicker;
@property (nonatomic, copy, setter = setOffImagePicker:) DKImagePicker offImagePicker;

@end
