//
//  UITableViewCell+Night.m
//  UITableViewCell+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "DKNightVersionManager.h"

#import "UITableViewCell+Night.h"
#import <objc/runtime.h>

@interface UITableViewCell ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UITableViewCell (Night)

- (DKColorPicker)backgroundColorPicker {
   
   return objc_getAssociatedObject(self, @selector(backgroundColorPicker));
}

- (void)setBackgroundColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(backgroundColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);

   if (nil != aPicker) {
      
      self.backgroundColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setBackgroundColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setBackgroundColor:"];
      
   } /* End else */
   
   return;
}

@end
