//
//  UITabBar+Night.h
//  UITabBar+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UITabBar (Night)

@property (nonatomic, copy, setter = setBarTintColorPicker:)            DKColorPicker barTintColorPicker;
@property (nonatomic, copy, setter = setBackgroundImagePicker:)         DKImagePicker backgroundImagePicker;
@property (nonatomic, copy, setter = setShadowImagePicker:)             DKImagePicker shadowImagePicker;

@property (nonatomic, copy, setter = setUnselectedItemTintColorPicker:) DKColorPicker unselectedItemTintColorPicker;

@end
