//
//  UIView+Night.m
//  UIView+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIView+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UIView ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIView (Night)

- (DKColorPicker)backgroundColorPicker {
   
   return objc_getAssociatedObject(self, @selector(backgroundColorPicker));
}

- (void)setBackgroundColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(backgroundColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);
   
   if (nil != aPicker) {
      
      self.backgroundColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setBackgroundColor:"];
      
   } /* End if () */
   else {
            
      [self.pickers removeObjectForKey:@"setBackgroundColor:"];
      
   } /* End else */
   
   return;
}

- (DKColorPicker)tintColorPicker {
   
   return objc_getAssociatedObject(self, @selector(tintColorPicker));
}

- (void)setTintColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(tintColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);

   if (nil != aPicker) {
      
      self.tintColor = aPicker(self.themeManager.themeVersion);
      [self.pickers setValue:[aPicker copy] forKey:@"setTintColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setTintColor:"];
      
   } /* End else */
   
   return;
}

- (DKColorPicker)borderColorPicker {
   
   return objc_getAssociatedObject(self, @selector(borderColorPicker));
}

- (void)setBorderColorPicker:(DKColorPicker)aPicker {
   
   objc_setAssociatedObject(self, @selector(borderColorPicker), aPicker, OBJC_ASSOCIATION_COPY_NONATOMIC);

   if (nil != aPicker) {
      
      self.layer.borderColor  = aPicker(self.themeManager.themeVersion).CGColor;
      [self.pickers setValue:[aPicker copy] forKey:@"setBorderColor:"];
      
   } /* End if () */
   else {
      
      [self.pickers removeObjectForKey:@"setBorderColor:"];
      
   } /* End else */
   
   return;
}

@end
